//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VideoShop2.rc
//
#define ID_CUSTAPE_ADD                  3
#define ID_TAPE_DELETE                  3
#define ID_CUSTAPE_DELETE               4
#define ID_CUSTAPE_UPDATE               5
#define ID_CUSTAPE_COMPLETE             6
#define IDD_ABOUTBOX                    100
#define IDD_VIDEOSHOP2_FORM             101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_MAINFRAME                   128
#define IDR_VIDEOSTYPE                  129
#define IDD_CUSTAPE_DLG                 130
#define IDD_TAPE_DLG                    131
#define IDD_INSTAPE_DLG                 132
#define IDC_NAME_EDIT                   1000
#define IDC_TEL_EDIT                    1001
#define IDC_ADDRESS_EDIT                1002
#define IDC_TAPE_LIST                   1003
#define IDC_CODE_EDIT                   1004
#define IDC_TITLE_EDIT                  1005
#define IDC_CUSNAME_EDIT                1006
#define IDC_INDAY_EDIT                  1006
#define IDC_CUSCODE_EDIT                1007
#define IDC_DIRECTOR_EDIT               1007
#define IDC_TITLE_LIST                  1008
#define IDC_ACTOR_EDIT                  1008
#define IDC_RENTDAY_EDIT                1009
#define IDC_MONEY_EDIT                  1009
#define IDC_RECDAY_EDIT                 1010
#define IDC_TAPETTLE_EDIT               1011
#define IDC_TAPECODE_EDIT               1012
#define IDC_ADD_BTN                     1015
#define IDC_ADDCANCEL_BTN               1016
#define IDC_DELETE_BTN                  1017
#define ID_RECORD_UPDATE                32771
#define ID_RECORD_ADDTAPE               32772
#define ID_RECORD_CUSTOM                32774
#define ID_RECORD_TAPE                  32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
