//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.3053
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BindingSourceDemo.MyWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebService.MyServiceSoap")]
    public interface MyServiceSoap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 GetNamesResult이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNames", ReplyAction="*")]
        BindingSourceDemo.MyWebService.GetNamesResponse GetNames(BindingSourceDemo.MyWebService.GetNamesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNames", Namespace="http://tempuri.org/", Order=0)]
        public BindingSourceDemo.MyWebService.GetNamesRequestBody Body;
        
        public GetNamesRequest() {
        }
        
        public GetNamesRequest(BindingSourceDemo.MyWebService.GetNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNamesRequestBody {
        
        public GetNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BindingSourceDemo.MyWebService.GetNamesResponseBody Body;
        
        public GetNamesResponse() {
        }
        
        public GetNamesResponse(BindingSourceDemo.MyWebService.GetNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BindingSourceDemo.MyWebService.ArrayOfString GetNamesResult;
        
        public GetNamesResponseBody() {
        }
        
        public GetNamesResponseBody(BindingSourceDemo.MyWebService.ArrayOfString GetNamesResult) {
            this.GetNamesResult = GetNamesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MyServiceSoapChannel : BindingSourceDemo.MyWebService.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<BindingSourceDemo.MyWebService.MyServiceSoap>, BindingSourceDemo.MyWebService.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BindingSourceDemo.MyWebService.GetNamesResponse BindingSourceDemo.MyWebService.MyServiceSoap.GetNames(BindingSourceDemo.MyWebService.GetNamesRequest request) {
            return base.Channel.GetNames(request);
        }
        
        public BindingSourceDemo.MyWebService.ArrayOfString GetNames() {
            BindingSourceDemo.MyWebService.GetNamesRequest inValue = new BindingSourceDemo.MyWebService.GetNamesRequest();
            inValue.Body = new BindingSourceDemo.MyWebService.GetNamesRequestBody();
            BindingSourceDemo.MyWebService.GetNamesResponse retVal = ((BindingSourceDemo.MyWebService.MyServiceSoap)(this)).GetNames(inValue);
            return retVal.Body.GetNamesResult;
        }
    }
}
