//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="StockQuote", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class StockQuote : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string ChangeField;
    
    private string CompanyNameField;
    
    private string DateOfTradeField;
    
    private string DaysRangeField;
    
    private string LastTradePriceField;
    
    private string OpenField;
    
    private string PercentageChangeField;
    
    private string PreviousCloseField;
    
    private string TimeOfTradeField;
    
    private string VolumeField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Change
    {
        get
        {
            return this.ChangeField;
        }
        set
        {
            this.ChangeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string CompanyName
    {
        get
        {
            return this.CompanyNameField;
        }
        set
        {
            this.CompanyNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DateOfTrade
    {
        get
        {
            return this.DateOfTradeField;
        }
        set
        {
            this.DateOfTradeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DaysRange
    {
        get
        {
            return this.DaysRangeField;
        }
        set
        {
            this.DaysRangeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string LastTradePrice
    {
        get
        {
            return this.LastTradePriceField;
        }
        set
        {
            this.LastTradePriceField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Open
    {
        get
        {
            return this.OpenField;
        }
        set
        {
            this.OpenField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string PercentageChange
    {
        get
        {
            return this.PercentageChangeField;
        }
        set
        {
            this.PercentageChangeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string PreviousClose
    {
        get
        {
            return this.PreviousCloseField;
        }
        set
        {
            this.PreviousCloseField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string TimeOfTrade
    {
        get
        {
            return this.TimeOfTradeField;
        }
        set
        {
            this.TimeOfTradeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Volume
    {
        get
        {
            return this.VolumeField;
        }
        set
        {
            this.VolumeField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IYahooQuotes")]
public interface IYahooQuotes
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYahooQuotes/TestService", ReplyAction="http://tempuri.org/IYahooQuotes/TestServiceResponse")]
    string TestService(int intParam);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IYahooQuotes/GetQuoteForStockSymbol", ReplyAction="http://tempuri.org/IYahooQuotes/GetQuoteForStockSymbolResponse")]
    StockQuote GetQuoteForStockSymbol(string aSymbol);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IYahooQuotesChannel : IYahooQuotes, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class YahooQuotesClient : System.ServiceModel.ClientBase<IYahooQuotes>, IYahooQuotes
{
    
    public YahooQuotesClient()
    {
    }
    
    public YahooQuotesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public YahooQuotesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YahooQuotesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public YahooQuotesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string TestService(int intParam)
    {
        return base.Channel.TestService(intParam);
    }
    
    public StockQuote GetQuoteForStockSymbol(string aSymbol)
    {
        return base.Channel.GetQuoteForStockSymbol(aSymbol);
    }
}
