//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MultiLook.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MULTILOOK_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_MULTILTYPE                  129
#define IDB_TAB                         130
#define IDC_TAB1                        1000
#define IDC_RICHEDIT1                   1001
#define ID_FORM_VIEW                    32771
#define ID_PAINT_VIEW                   32773
#define ID_FONT_VIEW                    32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
