//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ComDlg.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_COMDLGTYPE                  129
#define IDD_FILE_DELETE                 130
#define IDC_DELETE                      1000
#define stc32                           0x045f
#define ID_COMDLG_COLOR                 32771
#define ID_COMDLG_OPEN                  32772
#define ID_COMDLG_SAVEAS                32773
#define ID_COMDLG_FONT                  32774
#define ID_COMDLG_PRINT                 32775
#define ID_COMDLG_PAGESETUP             32776
#define ID_COMDLG_FIND                  32777
#define ID_COMDLG_REPLACE               32778
#define ID_COMDLG_PRINTERSETUP          32779
#define ID_COMDLG_DELETE                32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
