//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ExplorerTest.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_EXPLORTYPE                  129
#define IDB_BIG_SHELL                   132
#define IDB_SHELL                       133
#define IDR_CONTEXTMENU                 135
#define IDD_INFO_DLG                    136
#define IDC_NAME                        1001
#define IDC_CHECK_READONLY              1002
#define IDC_CHECK_HIDDEN                1003
#define IDC_CHECK_ARCHIVE               1004
#define IDC_CHECK_SYSTEM                1005
#define IDC_KIND                        1006
#define IDC_POSITION                    1007
#define IDC_FILESIZE                    1008
#define IDC_CREATION                    1009
#define IDC_LAST_WRITE                  1010
#define IDC_LAST_ACCESS                 1011
#define IDC_FILE_NAME                   1012
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_FOLDER_NEW                   32771
#define ID_CONTEXT_CANCEL               32777
#define ID_INFORMATION                  32779
#define ID_FILE_RENAME                  32780
#define ID_FILE_DELETE                  32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
