//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://xdn-dcpark/WCF/person", ClrNamespace="xdndcpark.WCF.person")]

namespace xdndcpark.WCF.person
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstField;
        
        private string lastField;
        
        private string idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first
        {
            get
            {
                return this.firstField;
            }
            set
            {
                this.firstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last
        {
            get
            {
                return this.lastField;
            }
            set
            {
                this.lastField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://xdn-dcpark/WCF/echo/", ConfigurationName="IEchoService", CallbackContract=typeof(IEchoServiceCallback))]
public interface IEchoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:echo:string", ReplyAction="http://xdn-dcpark/WCF/echo/IEchoService/EchoResponse")]
    string Echo(string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xdn-dcpark/WCF/echo/IEchoService/EchoPerson", ReplyAction="http://xdn-dcpark/WCF/echo/IEchoService/EchoPersonResponse")]
    xdndcpark.WCF.person.Person EchoPerson(xdndcpark.WCF.person.Person p);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://xdn-dcpark/WCF/echo/IEchoService/EchoJobStart")]
    void EchoJobStart(string jobName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IEchoServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://xdn-dcpark/WCF/echo/IEchoService/EchoJobEnd")]
    void EchoJobEnd(string result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IEchoServiceChannel : IEchoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class EchoServiceClient : System.ServiceModel.DuplexClientBase<IEchoService>, IEchoService
{
    
    public EchoServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public EchoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public EchoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EchoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public EchoServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public string Echo(string msg)
    {
        return base.Channel.Echo(msg);
    }
    
    public xdndcpark.WCF.person.Person EchoPerson(xdndcpark.WCF.person.Person p)
    {
        return base.Channel.EchoPerson(p);
    }
    
    public void EchoJobStart(string jobName)
    {
        base.Channel.EchoJobStart(jobName);
    }
}
