//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pass.rc
//
#define IDW_PASSFORM                    1000
#define IDB_SETUP                       1001
#define IDR_AVI1                        1002
#define IDD_SETUP                       1003
#define IDC_MAIL                        1003
#define IDC_PATH                        1004
#define IDC_ANIMATE                     1006
#define IDS_PROPSHT_CAPTION             1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           1010
#endif
#endif
