// AddMyCalCom.idl : IDL source for AddMyCalCom.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AddMyCalCom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(5BBBB248-1758-4D73-9233-DEA81E132491),
		dual,
		helpstring("ICal Interface"),
		pointer_default(unique)
	]
	interface ICal : IDispatch
	{
		[id(1), helpstring("method Add")] HRESULT Add([in] int first, [in] int second);
		[propget, id(2), helpstring("property Result")] HRESULT Result([out, retval] int *pVal);
		[propput, id(2), helpstring("property Result")] HRESULT Result([in] int newVal);
		[id(3), helpstring("method StringTest")] HRESULT StringTest(BSTR str);
	};
	[
		object,
		uuid(723BC6C1-8EC3-49ad-97E6-5446CE23AE19),
		dual,
		helpstring("ICalEvent Interface"),
		pointer_default(unique)
	]
	interface ICalEvent : IDispatch
	{
		[id(1), helpstring("method ResultNumber")] HRESULT ResltNumber(int num);
		[id(2), helpstring("method Test")] HRESULT Test(BSTR str);
	};

[
	uuid(2BE554A9-12E7-4580-A423-8893B30D1B0E),
	version(1.0),
	helpstring("AddMyCalCom 1.0 Type Library")
]
library ADDMYCALCOMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	[
		uuid(7190E1C9-70F3-4493-A491-EB8F869AAA98),
		helpstring("_ICalEvent Interface")
	]
	dispinterface _ICalEvent
	{
		properties:
		methods:
		[id(1), helpstring("method ResultNumber")] HRESULT ResultNumber(int num);
		[id(2), helpstring("method Test")] HRESULT Test(BSTR str);
	};
	[
		uuid(63CAE2B0-B4AD-4972-B188-2A644353125C),
		helpstring("Cal Class")
	]
	coclass Cal
	{
		[default] interface ICal;
		[default, source] dispinterface _ICalEvent;
		[source] interface ICalEvent;
	};
};
