//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Movie.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MOVIE_FORM                  101
#define IDS_PROPSHT_CAPTION             102
#define IDD_PROPPAGE1                   103
#define IDD_PROPPAGE2                   104
#define IDD_PROPPAGE3                   105
#define IDD_PROPPAGE4                   106
#define IDR_MAINFRAME                   128
#define IDR_MOVIETYPE                   129
#define IDD_MODAL                       130
#define IDB_BATMAN                      132
#define IDB_BATGIRL                     133
#define IDB_FORM_IMAGE1                 134
#define IDB_MODELESS                    135
#define IDB_FORM_IMAGE2                 136
#define IDR_AVI1                        137
#define IDD_MODELESS                    141
#define IDB_LIST                        143
#define IDB_LARGE                       144
#define IDR_WAVE1                       153
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_CORD_X                      1003
#define IDC_BUTTON1                     1004
#define IDC_CORD_Y                      1004
#define IDC_BUTTON2                     1005
#define IDC_BUTTON3                     1006
#define IDC_BUTTON4                     1007
#define IDC_COMBO_ADD                   1008
#define IDC_LIST                        1008
#define IDC_COMBO1                      1009
#define IDC_STATIC_COLOR                1009
#define IDC_REPORT                      1009
#define IDC_LIST1                       1010
#define IDC_RADIO1                      1011
#define IDC_RADIO2                      1012
#define IDC_SCROLLBAR1                  1013
#define IDC_STATIC1                     1014
#define IDC_STATIC2                     1015
#define IDC_STATIC3                     1016
#define IDC_STATIC4                     1017
#define IDC_STATIC_COUNT                1018
#define IDC_FORM_MODAL                  1019
#define IDC_LIST_ADD                    1019
#define IDC_STATIC_LIST                 1020
#define IDC_STATIC_COMBO                1021
#define IDC_FORM_MODELESS               1021
#define IDC_RED_VALUE                   1022
#define IDC_FORM_PROPERTY               1022
#define IDC_BLUE_VALUE                  1023
#define IDC_FORM_WIZARD                 1023
#define IDC_GREEN_VALUE                 1024
#define IDC_FORM_COUNT                  1025
#define IDC_STATIC_IMAGE                1026
#define IDC_FORM_COLOR                  1027
#define IDC_FORM_IMAGE                  1028
#define IDC_ANIMATE1                    1032
#define IDC_PROGRESS1                   1033
#define IDC_SPIN1                       1034
#define IDC_SLIDER1                     1035
#define IDC_SLIDER2                     1036
#define IDC_TREE1                       1036
#define IDC_SLIDER3                     1037
#define IDC_RED                         1038
#define IDC_GREEN                       1039
#define IDC_BLUE                        1040
#define IDC_COLOR_SHOW                  1041
#define IDC_SELECT_TREE                 1044
#define IDC_SELECT_LIST                 1045
#define IDC_ICON_TYPE                   1050
#define IDC_SMALL_TYPE                  1051
#define IDC_LIST_TYPE                   1052
#define IDC_REPORT_TYPE                 1053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
